version: '3.5'

services:
  r:
    build:
      context: images/ohdsi-r-base
      args:
        GITHUB_PAT: ${GITHUB_PAT}
    depends_on:
      - postgresql
    networks:
      - default
      - ohdsi-postgresql
    volumes:
      - ./src/r:/scripts
      - ./data/vocabulary:/data/vocabulary
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.atlas.rule=Host(`${HOSTNAME}`) && PathPrefix(`/shiny`)"
      - "traefik.http.services.atlas.loadbalancer.server.port=7249"
  

  achilles:
    image: thehyve/ohdsi-achilles:1.6.3
    depends_on:
      - postgresql
    networks:
      - default
      - ohdsi-postgresql
    environment:
      - ACHILLES_DB_URI=postgresql://postgres:${POSTGRESQL_PASSWORD}@postgresql/ohdsi
      - ACHILLES_VOCAB_SCHEMA=vocab
      - ACHILLES_CDM_SCHEMA=cdm5
      - ACHILLES_RES_SCHEMA=cdm5
      - ACHILLES_SOURCE="Synthea"

  etl-synthea:
    image: thehyve/ohdsi-etl-synthea
    depends_on:
      - postgresql
    networks:
      - default
      - ohdsi-postgresql
    volumes:
      - synthea_data:/data/synthea
    environment:
      - SYNTHEA_DB_URI=postgresql://postgres:${POSTGRESQL_PASSWORD}@postgresql/ohdsi
      - SYNTHEA_VOCAB_SCHEMA=vocab

  synthea:
    image: thehyve/synthea:2.5.0
    build:
      context: images/synthea
      args:
        SYNTHEA_VERSION: "2.5.0"
    volumes:
      - synthea_data:/code/output
    command: ["/code/run_synthea"]

  notebook:
    image: thehyve/ohdsi-jupyter-notebook
    build:
      context: images/notebook

volumes:
  synthea_data: {}
