DROP SCHEMA ${RAW_SCHEMA} CASCADE;
DROP SCHEMA ${CDM_SCHEMA} CASCADE;
DROP SCHEMA ${RESULTS_SCHEMA} CASCADE;

CREATE SCHEMA ${RAW_SCHEMA};
CREATE SCHEMA ${CDM_SCHEMA};
CREATE SCHEMA ${RESULTS_SCHEMA};
